# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainLayout4.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PMP(object):
    def setupUi(self, PMP):
        PMP.setObjectName("PMP")
        PMP.resize(549, 411)
        self.centralwidget = QtWidgets.QWidget(PMP)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 551, 371))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.homeTab = QtWidgets.QWidget()
        self.homeTab.setObjectName("homeTab")
        self.pushButtonSearchWhole = QtWidgets.QPushButton(self.homeTab)
        self.pushButtonSearchWhole.setGeometry(QtCore.QRect(20, 300, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButtonSearchWhole.setFont(font)
        self.pushButtonSearchWhole.setObjectName("pushButtonSearchWhole")
        self.pushButtonSearchRT = QtWidgets.QPushButton(self.homeTab)
        self.pushButtonSearchRT.setGeometry(QtCore.QRect(350, 300, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButtonSearchRT.setFont(font)
        self.pushButtonSearchRT.setObjectName("pushButtonSearchRT")
        self.frameHome = QtWidgets.QFrame(self.homeTab)
        self.frameHome.setGeometry(QtCore.QRect(20, 20, 501, 266))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameHome.sizePolicy().hasHeightForWidth())
        self.frameHome.setSizePolicy(sizePolicy)
        self.frameHome.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameHome.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameHome.setLineWidth(1)
        self.frameHome.setMidLineWidth(0)
        self.frameHome.setObjectName("frameHome")
        self.textBrowserSearch = QtWidgets.QTextBrowser(self.frameHome)
        self.textBrowserSearch.setGeometry(QtCore.QRect(1, 24, 499, 241))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textBrowserSearch.setFont(font)
        self.textBrowserSearch.setObjectName("textBrowserSearch")
        self.labelReport = QtWidgets.QLabel(self.frameHome)
        self.labelReport.setGeometry(QtCore.QRect(9, 3, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelReport.setFont(font)
        self.labelReport.setObjectName("labelReport")
        self.pushButtonStop = QtWidgets.QPushButton(self.homeTab)
        self.pushButtonStop.setGeometry(QtCore.QRect(220, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButtonStop.setFont(font)
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.tabWidget.addTab(self.homeTab, "")
        self.ruleTab = QtWidgets.QWidget()
        self.ruleTab.setObjectName("ruleTab")
        self.listWidgetRuleNo = QtWidgets.QListWidget(self.ruleTab)
        self.listWidgetRuleNo.setGeometry(QtCore.QRect(21, 30, 221, 181))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.listWidgetRuleNo.setFont(font)
        self.listWidgetRuleNo.setObjectName("listWidgetRuleNo")
        item = QtWidgets.QListWidgetItem()
        self.listWidgetRuleNo.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetRuleNo.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetRuleNo.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetRuleNo.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetRuleNo.addItem(item)
        self.pushButtonRuleAdd = QtWidgets.QPushButton(self.ruleTab)
        self.pushButtonRuleAdd.setGeometry(QtCore.QRect(247, 76, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButtonRuleAdd.setFont(font)
        self.pushButtonRuleAdd.setObjectName("pushButtonRuleAdd")
        self.pushButtonRuleApplyOk = QtWidgets.QPushButton(self.ruleTab)
        self.pushButtonRuleApplyOk.setGeometry(QtCore.QRect(247, 30, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButtonRuleApplyOk.setFont(font)
        self.pushButtonRuleApplyOk.setObjectName("pushButtonRuleApplyOk")
        self.listWidgetRuleOK = QtWidgets.QListWidget(self.ruleTab)
        self.listWidgetRuleOK.setGeometry(QtCore.QRect(303, 30, 221, 181))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setItalic(False)
        self.listWidgetRuleOK.setFont(font)
        self.listWidgetRuleOK.setObjectName("listWidgetRuleOK")
        self.pushButtonRuleApplyNo = QtWidgets.QPushButton(self.ruleTab)
        self.pushButtonRuleApplyNo.setGeometry(QtCore.QRect(247, 170, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButtonRuleApplyNo.setFont(font)
        self.pushButtonRuleApplyNo.setObjectName("pushButtonRuleApplyNo")
        self.pushButtonPasswd = QtWidgets.QPushButton(self.ruleTab)
        self.pushButtonPasswd.setGeometry(QtCore.QRect(190, 260, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButtonPasswd.setFont(font)
        self.pushButtonPasswd.setObjectName("pushButtonPasswd")
        self.line = QtWidgets.QFrame(self.ruleTab)
        self.line.setGeometry(QtCore.QRect(10, 220, 521, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButtonRuleDelete = QtWidgets.QPushButton(self.ruleTab)
        self.pushButtonRuleDelete.setGeometry(QtCore.QRect(247, 122, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButtonRuleDelete.setFont(font)
        self.pushButtonRuleDelete.setObjectName("pushButtonRuleDelete")
        self.tabWidget.addTab(self.ruleTab, "")
        self.helpTab = QtWidgets.QWidget()
        self.helpTab.setObjectName("helpTab")
        self.frameHelp = QtWidgets.QFrame(self.helpTab)
        self.frameHelp.setGeometry(QtCore.QRect(20, 20, 501, 266))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameHelp.sizePolicy().hasHeightForWidth())
        self.frameHelp.setSizePolicy(sizePolicy)
        self.frameHelp.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameHelp.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameHelp.setLineWidth(1)
        self.frameHelp.setMidLineWidth(0)
        self.frameHelp.setObjectName("frameHelp")
        self.label = QtWidgets.QLabel(self.helpTab)
        self.label.setGeometry(QtCore.QRect(190, 300, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(10)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.helpTab, "")
        PMP.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PMP)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 21))
        self.menubar.setObjectName("menubar")
        PMP.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PMP)
        self.statusbar.setObjectName("statusbar")
        PMP.setStatusBar(self.statusbar)

        self.retranslateUi(PMP)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PMP)

    def retranslateUi(self, PMP):
        _translate = QtCore.QCoreApplication.translate
        PMP.setWindowTitle(_translate("PMP", "MainWindow"))
        self.pushButtonSearchWhole.setText(_translate("PMP", "Whole System Search"))
        self.pushButtonSearchRT.setText(_translate("PMP", "Real Time Search"))
        self.labelReport.setText(_translate("PMP", "Report"))
        self.pushButtonStop.setText(_translate("PMP", "STOP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.homeTab), _translate("PMP", "Home"))
        __sortingEnabled = self.listWidgetRuleNo.isSortingEnabled()
        self.listWidgetRuleNo.setSortingEnabled(False)
        item = self.listWidgetRuleNo.item(0)
        item.setText(_translate("PMP", "Keyword1"))
        item = self.listWidgetRuleNo.item(1)
        item.setText(_translate("PMP", "Keyword2"))
        item = self.listWidgetRuleNo.item(2)
        item.setText(_translate("PMP", "Keyword3"))
        item = self.listWidgetRuleNo.item(3)
        item.setText(_translate("PMP", "Keyword4"))
        item = self.listWidgetRuleNo.item(4)
        item.setText(_translate("PMP", "Keyword5"))
        self.listWidgetRuleNo.setSortingEnabled(__sortingEnabled)
        self.pushButtonRuleAdd.setText(_translate("PMP", "+"))
        self.pushButtonRuleApplyOk.setText(_translate("PMP", "->"))
        self.pushButtonRuleApplyNo.setText(_translate("PMP", "<-"))
        self.pushButtonPasswd.setText(_translate("PMP", "Password"))
        self.pushButtonRuleDelete.setText(_translate("PMP", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ruleTab), _translate("PMP", "Rules Setting"))
        self.label.setText(_translate("PMP", "copyright 어쩌구저쩌구..........."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.helpTab), _translate("PMP", "Help"))

