# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainLayout6.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import config_make.config_manager as cm
import config_make.config_manager_test as cmt


class Ui_PMP(object):
    def setupUi(self, PMP):
        PMP.setObjectName("PMP")
        PMP.resize(549, 411)
        self.centralwidget = QtWidgets.QWidget(PMP)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 551, 371))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.homeTab = QtWidgets.QWidget()
        self.homeTab.setObjectName("homeTab")
        self.pushButtonSearchWhole = QtWidgets.QPushButton(self.homeTab)
        self.pushButtonSearchWhole.setGeometry(QtCore.QRect(20, 300, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButtonSearchWhole.setFont(font)
        self.pushButtonSearchWhole.setObjectName("pushButtonSearchWhole")
        self.pushButtonSearchRT = QtWidgets.QPushButton(self.homeTab)
        self.pushButtonSearchRT.setGeometry(QtCore.QRect(350, 300, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButtonSearchRT.setFont(font)
        self.pushButtonSearchRT.setObjectName("pushButtonSearchRT")
        self.frameHome = QtWidgets.QFrame(self.homeTab)
        self.frameHome.setGeometry(QtCore.QRect(20, 20, 501, 266))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameHome.sizePolicy().hasHeightForWidth())
        self.frameHome.setSizePolicy(sizePolicy)
        self.frameHome.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameHome.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameHome.setLineWidth(1)
        self.frameHome.setMidLineWidth(0)
        self.frameHome.setObjectName("frameHome")
        self.textBrowserSearch = QtWidgets.QTextBrowser(self.frameHome)
        self.textBrowserSearch.setGeometry(QtCore.QRect(1, 24, 499, 241))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textBrowserSearch.setFont(font)
        self.textBrowserSearch.setObjectName("textBrowserSearch")
        self.labelReport = QtWidgets.QLabel(self.frameHome)
        self.labelReport.setGeometry(QtCore.QRect(9, 3, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelReport.setFont(font)
        self.labelReport.setText("")
        self.labelReport.setObjectName("labelReport")
        self.pushButtonStop = QtWidgets.QPushButton(self.homeTab)
        self.pushButtonStop.setGeometry(QtCore.QRect(220, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButtonStop.setFont(font)
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.tabWidget.addTab(self.homeTab, "")
        self.ruleTab = QtWidgets.QWidget()
        self.ruleTab.setObjectName("ruleTab")
        self.listWidgetRuleNo = QtWidgets.QListWidget(self.ruleTab)
        self.listWidgetRuleNo.setGeometry(QtCore.QRect(21, 30, 221, 261))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.listWidgetRuleNo.setFont(font)
        self.listWidgetRuleNo.setObjectName("listWidgetRuleNo")

        # a = cm.configlen()

        a = cmt.get_left_keyword_len()

        for i in range(0,a):
            item = QtWidgets.QListWidgetItem()
            self.listWidgetRuleNo.addItem(item)

        self.pushButtonRuleAdd = QtWidgets.QPushButton(self.ruleTab)
        self.pushButtonRuleAdd.setGeometry(QtCore.QRect(247, 100, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButtonRuleAdd.setFont(font)
        self.pushButtonRuleAdd.setObjectName("pushButtonRuleAdd")
        self.pushButtonRuleApplyOk = QtWidgets.QPushButton(self.ruleTab)
        self.pushButtonRuleApplyOk.setGeometry(QtCore.QRect(247, 30, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButtonRuleApplyOk.setFont(font)
        self.pushButtonRuleApplyOk.setObjectName("pushButtonRuleApplyOk")
        self.listWidgetRuleOK = QtWidgets.QListWidget(self.ruleTab)
        self.listWidgetRuleOK.setGeometry(QtCore.QRect(303, 30, 221, 261))

        # c = cm.rkeywordlen()
        c = cmt.get_rigth_keyword_len()
        for i in range(0,c):
            item = QtWidgets.QListWidgetItem()
            self.listWidgetRuleOK.addItem(item)

        font = QtGui.QFont()
        font.setPointSize(14)
        font.setFamily("Utsaah")
        font.setItalic(False)
        self.listWidgetRuleOK.setFont(font)
        self.listWidgetRuleOK.setObjectName("listWidgetRuleOK")
        self.pushButtonRuleApplyNo = QtWidgets.QPushButton(self.ruleTab)
        self.pushButtonRuleApplyNo.setGeometry(QtCore.QRect(247, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButtonRuleApplyNo.setFont(font)
        self.pushButtonRuleApplyNo.setObjectName("pushButtonRuleApplyNo")
        self.pushButtonRuleDelete = QtWidgets.QPushButton(self.ruleTab)
        self.pushButtonRuleDelete.setGeometry(QtCore.QRect(247, 170, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButtonRuleDelete.setFont(font)
        self.pushButtonRuleDelete.setObjectName("pushButtonRuleDelete")
        self.labelApplyNo = QtWidgets.QLabel(self.ruleTab)
        self.labelApplyNo.setGeometry(QtCore.QRect(90, 290, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.labelApplyNo.setFont(font)
        self.labelApplyNo.setObjectName("labelApplyNo")
        self.labelApplyOk = QtWidgets.QLabel(self.ruleTab)
        self.labelApplyOk.setGeometry(QtCore.QRect(370, 290, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        font.setItalic(False)
        self.labelApplyOk.setFont(font)
        self.labelApplyOk.setObjectName("labelApplyOk")
        self.tabWidget.addTab(self.ruleTab, "")
        self.helpTab = QtWidgets.QWidget()
        self.helpTab.setObjectName("helpTab")
        self.frameHelp = QtWidgets.QFrame(self.helpTab)
        self.frameHelp.setGeometry(QtCore.QRect(20, 20, 501, 266))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameHelp.sizePolicy().hasHeightForWidth())
        self.frameHelp.setSizePolicy(sizePolicy)
        self.frameHelp.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameHelp.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameHelp.setLineWidth(1)
        self.frameHelp.setMidLineWidth(0)
        self.frameHelp.setObjectName("frameHelp")
        self.line_2 = QtWidgets.QFrame(self.frameHelp)
        self.line_2.setGeometry(QtCore.QRect(140, 20, 20, 231))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(self.frameHelp)
        self.label.setGeometry(QtCore.QRect(50, 60, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButtonResetReg = QtWidgets.QPushButton(self.frameHelp)
        self.pushButtonResetReg.setGeometry(QtCore.QRect(270, 60, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        self.pushButtonResetReg.setFont(font)
        self.pushButtonResetReg.setObjectName("pushButtonResetReg")
        self.line = QtWidgets.QFrame(self.frameHelp)
        self.line.setGeometry(QtCore.QRect(10, 130, 481, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.frameHelp)
        self.label_2.setGeometry(QtCore.QRect(50, 180, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frameHelp)
        self.label_3.setGeometry(QtCore.QRect(170, 100, 311, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButtonChangePassword = QtWidgets.QPushButton(self.frameHelp)
        self.pushButtonChangePassword.setGeometry(QtCore.QRect(270, 180, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Utsaah")
        font.setPointSize(14)
        self.pushButtonChangePassword.setFont(font)
        self.pushButtonChangePassword.setObjectName("pushButtonChangePassword")
        self.tabWidget.addTab(self.helpTab, "")
        PMP.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PMP)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 21))
        self.menubar.setObjectName("menubar")
        PMP.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PMP)
        self.statusbar.setObjectName("statusbar")
        PMP.setStatusBar(self.statusbar)

        self.retranslateUi(PMP)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PMP)

    def retranslateUi(self, PMP):
        _translate = QtCore.QCoreApplication.translate
        PMP.setWindowTitle(_translate("PMP", "PMP"))
        self.pushButtonSearchWhole.setText(_translate("PMP", "Whole System Search"))
        self.pushButtonSearchRT.setText(_translate("PMP", "Real Time Search"))
        self.pushButtonStop.setText(_translate("PMP", "STOP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.homeTab), _translate("PMP", "Home"))
        __sortingEnabled = self.listWidgetRuleNo.isSortingEnabled()
        self.listWidgetRuleNo.setSortingEnabled(False)

        # a = cm.configlen()
        a = cmt.get_left_keyword_len()

        for i in range(0,a):
            item = self.listWidgetRuleNo.item(i)
            # b = cm.openconfig(i)
            b = cmt.left_configbox_i(i)
            item.setText(_translate("MainWindow", "%s" % b))

        # c = cm.rkeywordlen()
        c = cmt.get_rigth_keyword_len()

        for i in range(0,c):
            item = self.listWidgetRuleOK.item(i)
            # d = cm.openconfigright(i)
            d = cmt.right_configbox(i)
            item.setText(_translate("MainWindow", "%s" % d))

        self.listWidgetRuleNo.setSortingEnabled(__sortingEnabled)
        self.pushButtonRuleAdd.setText(_translate("PMP", "+"))
        self.pushButtonRuleApplyOk.setText(_translate("PMP", "->"))
        self.pushButtonRuleApplyNo.setText(_translate("PMP", "<-"))
        self.pushButtonRuleDelete.setText(_translate("PMP", "-"))
        self.labelApplyNo.setText(_translate("PMP", "Before Apply"))
        self.labelApplyOk.setText(_translate("PMP", "After Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ruleTab), _translate("PMP", "Rules Setting"))
        self.label.setText(_translate("PMP", "Registry"))
        self.pushButtonResetReg.setText(_translate("PMP", "Reset"))
        self.label_2.setText(_translate("PMP", "Password"))
        self.label_3.setText(_translate("PMP", "<레지스트리 초기화시 본 프로그램을 이용할 수 없습니다>"))
        self.pushButtonChangePassword.setText(_translate("PMP", "Change"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.helpTab), _translate("PMP", "Help"))
